package io.github.kvmy666.duostatusbar.ui
import io.github.kvmy666.duostatusbar.i18n.UiText

/** Explanations are resolved on demand so language changes never retain old labels. */
internal data class FeatureGuide(val title:String,val explanation:String,val use:String) {
    companion object {
        private val entries=listOf(
            FeatureGuide("Personalizar a barra","Liga o anel nesta orientação. O módulo precisa estar ativado no LSPosed e carregado no SystemUI. Desligar devolve os indicadores originais.","Comece aqui. Depois abra Visual para ajustar o desenho e Efeitos para escolher o comportamento."),
            FeatureGuide("Movimento suave","Permite animações no anel. Os sensores e desenhos são pausados quando não são necessários. Desligar mantém os estados visuais sem movimento.","Use para escolher entre movimento e uma barra mais discreta."),
            FeatureGuide("Check no desbloqueio","Depois do desbloqueio, o check ocupa o centro por 3 segundos. Sua saída termina antes da entrada do próximo ícone; nenhum Wi-Fi aparece atrás dele.","Use como confirmação rápida de que o telefone foi desbloqueado. O tempo único não altera estes 3 segundos."),
            FeatureGuide("Alternância de ícones","Estados secundários alternam com saída e entrada separadas. Música e gravações têm prioridade: o evento mais recente fica até terminar, e o Wi-Fi espera em segundo plano.","Use para reunir vários indicadores em um único anel. Segure o anel para ver todos no resumo, se essa opção estiver ligada."),
            FeatureGuide("Todos os indicadores","Inclui os estados que o Android consegue confirmar, como Bluetooth, privacidade, gravação, alarme e GPS. Um estado sem acesso ou sem evidência não é inventado.","Use para acompanhar o aparelho. A lista varia conforme os serviços disponíveis na sua versão do Android."),
            FeatureGuide("NFC","Mostra que o rádio NFC está ligado. Isso não confirma que um pagamento ou uma leitura aconteceu.","Use para lembrar de desligar o NFC quando não precisar."),
            FeatureGuide("Aviso de fones","Mostra os fones conectados. A porcentagem só aparece se o acessório informar a bateria: acima de 15% verde; 15% ou menos vermelho.","Use com fones Bluetooth compatíveis. Bateria desconhecida fica sem número, não vira zero."),
            FeatureGuide("Brilho durante a carga","Ao conectar o carregador, um brilho curto percorre o anel. Durante a carga há movimento moderado nos arcos, sem ocupar permanentemente o centro com o raio.","Use para identificar a carga rapidamente. Os outros estados continuam disponíveis enquanto carrega."),
            FeatureGuide("Anel musical","Usa a sessão de mídia do Android. Enquanto a música toca, ondas e progresso acompanham a reprodução. Ao pausar ou parar, o ícone deixa o centro.","Se o player não aparecer, conecte o app aos eventos do aparelho em Música e captura. Posição e duração dependem do que o player fornece."),
            FeatureGuide("Cores da capa","Extrai uma cor da capa localmente para pequenos detalhes do anel musical. A imagem não é enviada. Sem capa, usa a cor normal.","Ative junto do anel musical para combinar o detalhe com a faixa atual."),
            FeatureGuide("Previsão de carga","Estima o tempo até 100% usando a previsão do Android ou o ritmo observado. Precisa de amostras; Calculando significa que ainda não há dados suficientes.","Use como estimativa, não como horário garantido. Temperatura, carregador e uso do telefone mudam o resultado."),
            FeatureGuide("Captura de tela","Detecta capturas salvas por nome e pasta e mostra um obturador breve. Não abre a imagem e não detecta capturas privadas que não são salvas.","Permita identificar capturas salvas em Música e captura. O acesso é opcional e pode ser revogado no Android."),
            FeatureGuide("Volume no anel","Uma mudança de volume mostra o nível por um instante. O aviso termina e devolve o estado anterior com uma transição.","Use para conferir o volume sem manter outro painel aberto."),
            FeatureGuide("Tempo de gravação","Durante a gravação de tela, mostra a bolinha vermelha e o tempo desde a detecção. O indicador fica enquanto a gravação estiver ativa.","O tempo começa quando o módulo detecta a gravação. Uma projeção de tela também pode ser informada como captura pelo Android."),
            FeatureGuide("Resumo expansível","Segure o anel para abrir a ilha. Ela reúne estados, bateria, música e atalhos. Toque fora, em fechar ou em voltar para recolher.","Use para consultar todos os estados sem esperar o carrossel. Os controles musicais dependem da sessão ativa do player."),
            FeatureGuide("GPS com bússola","Gira a seta conforme o norte magnético quando o GPS é exibido. Requer um sensor de orientação; sem ele, a seta fica fixa. Não coleta coordenadas.","Use para orientação visual. Ímãs e capas podem alterar a bússola; ela não substitui navegação."),
            FeatureGuide("Desenhar os ícones","Revela os traços na entrada, depois da saída do anterior. A animação para quando o ícone está pronto.","Combine com fade. Silhuetas preenchidas também têm uma entrada suave."),
            FeatureGuide("Tempo único para todos","Aplica a permanência escolhida a todos os ícones secundários e aplicativos, nas duas orientações. Desligar libera tempos individuais sem perder os valores guardados.","Música e gravações ficam até terminar. Avisos curtos, como desbloqueio e captura, mantêm a própria duração."),
            FeatureGuide("Somente Wi-Fi ou dados","Mantém apenas a conexão de rede no centro e desliga alternância e efeitos. Os outros ajustes ficam guardados.","Use para um visual mínimo. Desligue para voltar a ver música, gravações e outros estados."),
            FeatureGuide("Transições com fade","Primeiro o ícone atual desaparece, depois o próximo entra. Saída e entrada nunca ficam sobrepostas. Se o tempo for curto, os fades são ajustados para caber.","Desligue para troca direta entre ícones. Os eventos ativos continuam com prioridade."),
            FeatureGuide("Pausar no bolso","Usa proximidade e orientação para pausar o desenho quando o aparelho parece estar no bolso ou virado para baixo. Retoma quando deixa essa condição.","Use para evitar animações invisíveis. Capas e sensores diferentes podem afetar a detecção."),
            FeatureGuide("Roteador Wi-Fi","Mostra o compartilhamento da conexão quando o Android confirma o roteador ativo. A animação não mede tráfego nem velocidade.","Use para lembrar que outros aparelhos podem estar usando sua rede."),
            FeatureGuide("Bateria fraca","Ao detectar carga abaixo de 10%, mostra três pulsos e mantém um ponto discreto. Não fica repetindo o aviso inteiro a cada atualização.","Use como aviso visual para carregar o telefone."),
            FeatureGuide("Acabamento de vidro","Acrescenta contorno e translucidez. O desfoque depende da ROM; quando indisponível, usa uma superfície translúcida. Pode ter custo gráfico.","Use para dar profundidade ao anel e à ilha. Desative se preferir reduzir efeitos gráficos."),
            FeatureGuide("Movimento com molas","Usa curvas suaves na expansão e no retorno, sem mudar o tempo de permanência dos ícones.","Use com as animações ligadas para uma expansão mais natural."),
            FeatureGuide("Alinhamento automático","Usa a altura do relógio da barra como referência. Seus deslocamentos continuam limitados ao espaço da barra; não move o anel para o centro da tela.","Use se o anel e o relógio parecem ter alturas diferentes."),
            FeatureGuide("Expansão ao acender","Expande o anel quando a tela acende e recolhe ao apagar. A velocidade da entrada controla este movimento, sem alterar o check de 3 segundos.","Use para acompanhar o ligar e desligar da tela."),
            FeatureGuide("Ocultar na câmera","Quando o módulo detecta uso da câmera, esconde o anel e seus toques. O check de desbloqueio tem prioridade; nenhum aplicativo é identificado nos logs.","Use para deixar a área da câmera mais limpa durante o uso."),
        )
        fun find(label:String)=entries.firstOrNull { UiText.t(it.title)==label || (it.title=="Movimento suave"&&label in listOf("Animações","Animations","Animaciones")) }
    }
}
